### ISSUE TITLE
Add android sdk to class path

### ISSUE THREAD

**Issue by TheWinrarz** [csci-362-fall-2018-01/TeamCorrect#1]
We need to figure out how to add the android sdk to the class path while compiling tests. I assume it's similar to adding joda/junit but I can't find a jar file for it. All the guides I have found so far detail downloading it through android-studio but obviously that won't work when running a bash script. Not entirely necessary atm but we have to comment out some import statements. Our tests would have more efficacy if this was rectified

**Comment by HannahCarl** [comment]
We added the libraries necessary for our 25 test cases and can be seen in our folder "testCasesExecutables"
